project:
  type: book
  output-dir: docs

book:
  title: "Quantitative Social Research: On-line textbook"
  author: "Albert Varela"
  date: "2026/09/17"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_categorical.qmd
    - 03_continuous.qmd
    - 04_wrangling.qmd
    - 05_inference.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

