project:
  type: book
  output-dir: docs
  
resources:
  - slides/**

book:
  title: "Quantitative Social Research: On-line textbook"
  author: "Albert Varela"
  date: last-modified
  date-format: "D MMMM YYYY"
  chapters:
    - index.qmd
    - 00_intro.qmd
    - 01_categorical.qmd
    - 02_continuous.qmd
    - 03_wrangling.qmd
    - 04_inference.qmd
    - summary.qmd
    - 12_slides.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand

editor: visual

