{
  "hash": "8a908e19a48e98774fec8900ff27205f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Describing Categorical data\"\n---\n\n\n\n\n\n\n\n\n## Introduction\n\nIn this workshop we will get to grips with the basics of describing categorical data using RStudio. To follow this guide you should have first watched the video lectures on the VLE where each of the techniques here used are discussed in detail. Also on the VLE, you will find RStudio video tutorials that elaborate on this workshop guide.\n\nThe dataset we will analyse the \"2012 UK Omnibus Poverty and Social Exclusion Survey: Necessities of Life\" which is an\n\n> 'attitudinal survey aimed to identify what the population as a whole think are 'necessities': things that everyone should be able to afford and which no one should have to go without. Data were collected in Northern Ireland Statistics and Research Agency (NISRA), and in Great Britain (Scotland, England and Wales) by NatCen Social Research'.\n\nYou can find the dataset and relevant documentation in the UK Data Service by clicking this [link](https://beta.ukdataservice.ac.uk/datacatalogue/studies/study?id=7878). If interested in finding out more, you can read a report on the main findings [here](https://www.poverty.ac.uk/pse-research/what-do-we-think-we-need)\n\nThe substantive questions that drive this workshop are:\n\n1.  to what extent do UK residents regard a range of goods and services as necessary or merely desirable?\n2.  to what extent do perceptions of necessities vary across relevant socio-demographic groups?\n\nTo answer these questions we will learn about and use in practice the following analytical techniques:\n\n-   Numerical Summaries\n    -   Univariate frequency tables\n    -   Bivariate contingency tables\n-   Visualisation\n    -   Univariate bar plots\n    -   Bivariate clustered and Stacked bar plots\n\nYou will notice that these are the very same techniques you learnt about in the quantitative part of Level 2 Research Methods, so none of this material should be new to you. Having said this, we will be able to explore some aspects in a bit more detail to strengthen both your intuitive and statistical understanding of what the techniques are doing.\n\n## Data and libraries\n\nAssuming that you are already initialised RStudio in your computer and you have opened a project located in a folder containing the dataset file, the first steps is to load the dataset, call a number of packages that are necessary to run the code for this workshop:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load R packages\nlibrary(tidyverse)\nlibrary(knitr)\nlibrary(janitor)\nlibrary(scales)\nlibrary(ggstats)\n\n# load data\nload(\"pse_omni.Rdata\")\n```\n:::\n\n\n\n\n\n\n\n\nIf you want to have a quick look at the dataset to get a sense of what it is like, you can use the functions *glimpse() - list of variables and values -* or *view()* - the dataset in spreadsheet form - with the dataset called **omni** - this is not shown in the guide as it takes up multiple pages!\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(omni)\n```\n:::\n\n\n\n\n\n\n\n\nWe will then move straight to the analysis.\n\n## Numerical description of categorical data:\n\n### Base R\n\nTo describe the univariate distribution of a categorical variable we use frequency tables. Frequency tables can be produced in R using the function **table()** which can report both raw counts and percentages depending on how we specify the code.\n\nWe begin by describing the univariate distribution as raw counts of respondents for each category of the variable tv.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(omni$tv)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNecessary Desirable \n     1013       892 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nThe table shows that 1013 respondents say that having a TV is a necessity whereas 892 answer that it is simply desirable.\n\nBased on manipulating these raw counts we can calculate other quantities. In order to manipulate this table we need to store it in memory and give it a name, in this case *tabtv*\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We create an object call tabtv that contains the distribution of variable \"tv\" in the dataset omni\ntabtv <- table(omni$tv)\n\n# We ask R to display the new object \"tabtv\"\ntabtv\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNecessary Desirable \n     1013       892 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nThe first thing we can do is to add margins to the tabtv table - i.e. the sum of all observations contained in your table - using the function *addmargins()*\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naddmargins(tabtv)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNecessary Desirable       Sum \n     1013       892      1905 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nWe can also express the numbers in the table as proportions or percentages\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# as proportion\nprop.table(tabtv)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNecessary Desirable \n0.5317585 0.4682415 \n```\n\n\n:::\n\n```{.r .cell-code}\n#as percentage\nprop.table(tabtv)*100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNecessary Desirable \n 53.17585  46.82415 \n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n### Tidyverse\n\nYou can produce the same results using tidyverse functions. The tidyverse is a family of packages that have consistent coding principles and data handling conventions. For a detailed treatment of the tidyverse see the book [R for Data Science (2nd Edition)](https://r4ds.hadley.nz) by Wickham, Çetinkaya-Rundel and Grolemund.\n\nA key element of the tidyverse is the use of the pipe operator **\\|\\>** *(hotkey: command/ctrl + shift + m*) which allow us to write sequences or chains of functions - a bit like a baking recipe as shown in figure 1.\n\n![Piping in R (\\@ArthurWelle)](images/Screenshot%202024-10-01%20at%2017.44.34.png){width=\"353\"}\n\nHere's an example of how we create a frequency table in R using tidyverse functions or verbs and the pipe operator:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomni |> # dataset \n  drop_na(tv) |> # drop missing values from variable tv\n  group_by(tv) |> # across the response categories\n  summarise(n = n()) |> # count the respondents\n  mutate(perc = n / sum(n) * 100) |> \n  kable() # render nice looking table\n```\n\n::: {.cell-output-display}\n\n\n|tv        |    n|     perc|\n|:---------|----:|--------:|\n|Necessary | 1013| 53.17585|\n|Desirable |  892| 46.82415|\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nor using the function *count()*\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomni |> # dataset\n  drop_na(tv) |> # drop missing values from variable tv\n  count(tv) |> # count the respondents in each category\n  mutate(perc = n / sum(n) * 100) |> \n  kable() # render nice looking table\n```\n\n::: {.cell-output-display}\n\n\n|tv        |    n|     perc|\n|:---------|----:|--------:|\n|Necessary | 1013| 53.17585|\n|Desirable |  892| 46.82415|\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nTo round percentages up to 2 digits you can use the *round()* function\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomni |> # dataset\n  drop_na(tv) |> # drop missing values from variable tv\n  count(tv) |> # count the respondents in each category\n  mutate(perc = round(n / sum(n) * 100, 2)) |> # calculate percentage\n  kable() # render nice looking table\n```\n\n::: {.cell-output-display}\n\n\n|tv        |    n|  perc|\n|:---------|----:|-----:|\n|Necessary | 1013| 53.18|\n|Desirable |  892| 46.82|\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nOr you can use the function *percent* from the package **scales** which will also add the % sign\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomni |> # dataset\n  drop_na(tv) |> # drop missing values from variable tv\n  count(tv) |> # count the respondents in each category\n  mutate(perc = percent(n / sum(n), 0.01)) |> # calculate percentage\n  kable() # render nice looking table\n```\n\n::: {.cell-output-display}\n\n\n|tv        |    n|perc   |\n|:---------|----:|:------|\n|Necessary | 1013|53.18% |\n|Desirable |  892|46.82% |\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nFinally, the *tabyl* function (from the **janitor** package) makes it quite easy to produce nice tables, which becomes particularly useful for contingency tables discussed further below.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomni |> \n  drop_na(tv) |> \n  tabyl(tv) |> # create frequency table\n  adorn_pct_formatting(digits = 1) |> # choose number of decimals\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|tv        |    n|percent |\n|:---------|----:|:-------|\n|Necessary | 1013|53.2%   |\n|Desirable |  892|46.8%   |\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n## Graphical representation of univariate categorical data:\n\nWith ggplot we can create bar charts easily using the *geom_bar* option. The basic syntax is as follows:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Basic barplot\nggplot(data = omni, aes(x = tv)) +\n  geom_bar(stat = \"count\")\n```\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\nNotice that R ggplot creates a bar for the missing values (called NA). This NA bar draws away our attention from the Necessary and Desirable bars and could potentially distort the plot as a whole. We will remove the missing values by subsetting the data we input into the graph. To subset the data we use the following line when defining the data in ggplot: **omni\\[!is.na(omni\\$tv), \\]**\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Eliminate missing value category from the chart with (omni[!is.na(omni$tv), ]\nggplot(omni[!is.na(omni$tv), ], aes(x=tv)) +\n  geom_bar(stat=\"count\")\n```\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\nAlternatively we can use the function **complete.cases()** which is a bit more readable and produces the same result:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Eliminate missing value category from the chart with (omni[complete.cases(omni$tv), ]\nggplot(omni[complete.cases(omni$tv), ], aes(x=tv)) +\n  geom_bar(stat=\"count\")\n```\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\nOften you may want to plot proportions rather than counts, which can be achieved by changing the aesthetics' options. In this case, after declaring the variables write a **comma** and add **after_stat(prop), group = 1**:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = omni[complete.cases(omni$tv), ], aes(x=tv, y = after_stat(prop), group = 1)) +\n  geom_bar(stat=\"count\") \n```\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\nSince percentages are basically proportions multiplied by 100, we can have percentages on our plot by re-scaling (changing the scale) of the vertical axis using the option *scale_y_continuous(labels = scales::percent)*\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# If you want proportions, you need to modify the aesthetics options for the y axis\n\nggplot(data = omni[complete.cases(omni$tv), ], \n       aes(x=tv, y = after_stat(prop), group = 1)) +\n  geom_bar(stat=\"count\") + \n  scale_y_continuous(labels = scales::percent)\n```\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\nOr using the **tidyverse** you can integrate the specification of the ggplot graphs as part of a wider sequence of functions applied to the same data:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomni |> \n  drop_na(tv) |> \n  ggplot() +\n  geom_bar(aes( x = tv, y = after_stat(prop), group = 1)) +\n  scale_y_continuous(labels = scales::percent)\n```\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\nFinally, we should change the labels in the plot and add a title to make it more informative\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomni |> \n  drop_na(tv) |> \n  ggplot() +\n  geom_bar(aes( x = tv, y = after_stat(prop), group = 1)) +\n  scale_y_continuous(labels = scales::percent) +\n  xlab(\"Is a TV set necessary?\") + # change the x axis label\n  ylab(\"Percentage of respondents\") + # change the y axis label\n  ggtitle(\"A majority of respondents think a TV is necessary\") # change the main title of the graph\n```\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\nYou can also use specify labels and title within the function **labs** and produce the exact same results:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomni |> \n  drop_na(tv) |> \n  ggplot() +\n  geom_bar(aes( x = tv, y = after_stat(prop), group = 1)) +\n  labs(x = \"Is a TV set necessary?\", # specify x-axis lab\n       y = \"Percentage of respondents\", # specify y-axis lab\n       caption = \"Poverty and Social Exclusion Survey 2012\",\n       title = \"A majority of respondents think a TV is necessary\")  # main title\n```\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\n## Exercise I\n\nProvide the code necessary to calculate and plot the univariate distribution (as counts and percentages) of respondents according to whether they think having a \"a damp-free house\" (variable *nodamp*) is necessary as opposed to just desirable. You should obtain the following results:\n\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNecessary Desirable \n    94.47      5.53 \n```\n\n\n:::\n\n::: {.cell-output-display}\n\n\n|nodamp    |    n|   percent|\n|:---------|----:|---------:|\n|Necessary | 1811| 94.470527|\n|Desirable |  106|  5.529473|\n\n\n:::\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-20-2.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\n## Working with bivariate categorical data\n\nAfter learning how to produce a frequency table, we move onto contingency tables or crosstabulations. Contingency tables help us represent the cross-classification of two or more categorical variables - i.e. how individuals are classified simultaneously in the categories of more than one variable.\n\nFor instance, we may want to find out whether one's perception of TV as a necessity or a mere desire depends on past employment status. Not unlike the comparisons of pay between men and women (or levels of educational achievement) here we also compare the distribution of attitudes towards different goods between individuals classified in different socioeconomic categories.\n\n### Base R\n\nWe use again the function **table()** but this time we specify 2 variables as **table(var1, var2)**.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(omni$paidwork, omni$tv)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     \n      Necessary Desirable\n  Yes       438       516\n  No        571       365\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nNotice how now we obtain the marginal values for each category.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntvpw<-table(omni$paidwork, omni$tv) # create table object\naddmargins(tvpw) # add row, column and total sums\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     \n      Necessary Desirable  Sum\n  Yes       438       516  954\n  No        571       365  936\n  Sum      1009       881 1890\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nIt may be difficult to make sense of the raw counts, so it is often desirable to include either row or column proportions or percentages. This is easily done\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# row percentages\nprop.table(tvpw, 1)*100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     \n      Necessary Desirable\n  Yes  45.91195  54.08805\n  No   61.00427  38.99573\n```\n\n\n:::\n\n```{.r .cell-code}\n#column percentages (re-arrange the table with omni$tv in the rows)\ntvpw_inv<-table(omni$tv, omni$paidwork)\nprop.table(tvpw_inv, 2)*100\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           \n                 Yes       No\n  Necessary 45.91195 61.00427\n  Desirable 54.08805 38.99573\n```\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n### Tidyverse\n\nWe can achieve the same using tidyverse code, though it is decidedly more involved:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomni |> \n  drop_na(paidwork, tv) |> # remove missing values on two vars\n  group_by(paidwork, tv) |> #arrange by the categories of two vars\n  summarise(n = n()) |>  # count respondents in each combination\n  spread(tv, n) |> # organise them as contingency table\n  adorn_totals(c(\"row\", \"col\")) |> #add margins from tabyl\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|paidwork | Necessary| Desirable| Total|\n|:--------|---------:|---------:|-----:|\n|Yes      |       438|       516|   954|\n|No       |       571|       365|   936|\n|Total    |      1009|       881|  1890|\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nFor row percentages you would use:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomni |> \n  drop_na(paidwork, tv) |> \n  group_by(paidwork, tv) |>\n  summarise(n = n()) |> \n  mutate(prop=n/sum(n)) |> \n  select(-n) |> \n  spread(tv, prop) |> \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|paidwork | Necessary| Desirable|\n|:--------|---------:|---------:|\n|Yes      | 0.4591195| 0.5408805|\n|No       | 0.6100427| 0.3899573|\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nFor column percentages you could use:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomni |> \n  drop_na(paidwork, tv) |> \n  group_by(tv, paidwork) |> \n  summarise(n = n()) |> \n  mutate(prop=n/sum(n)) |> \n  select(-n) |> \n  spread(tv, prop) |> \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|paidwork | Necessary| Desirable|\n|:--------|---------:|---------:|\n|Yes      | 0.4340932| 0.5856981|\n|No       | 0.5659068| 0.4143019|\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nFinally, you could use *tabyl()* for row percentages\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomni |> \n  drop_na(paidwork, tv) |> \n  tabyl(paidwork, tv) |> \n  adorn_totals(c(\"row\", \"col\")) |> \n  adorn_percentages(\"row\") |> \n  adorn_pct_formatting(digits = 1) |> \n  adorn_ns() |> \n  adorn_title() |> \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|         |tv            |            |               |\n|:--------|:-------------|:-----------|:--------------|\n|paidwork |Necessary     |Desirable   |Total          |\n|Yes      |45.9%   (438) |54.1% (516) |100.0%   (954) |\n|No       |61.0%   (571) |39.0% (365) |100.0%   (936) |\n|Total    |53.4% (1,009) |46.6% (881) |100.0% (1,890) |\n\n\n:::\n:::\n\n\n\n\n\n\n\n\nOr column percentages\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomni |> \n  drop_na(paidwork, tv) |> \n  tabyl(paidwork, tv) |> \n  adorn_totals(c(\"row\", \"col\")) |> \n  adorn_percentages(\"col\") |> \n  adorn_pct_formatting(digits = 1) |> \n  adorn_ns() |> \n  adorn_title() |> \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|         |tv             |             |               |\n|:--------|:--------------|:------------|:--------------|\n|paidwork |Necessary      |Desirable    |Total          |\n|Yes      |43.4%   (438)  |58.6% (516)  |50.5%   (954)  |\n|No       |56.6%   (571)  |41.4% (365)  |49.5%   (936)  |\n|Total    |100.0% (1,009) |100.0% (881) |100.0% (1,890) |\n\n\n:::\n:::\n\n\n\n\n\n\n\n\n## Graphical representation of bivariate categorical data:\n\nContingency tables can also be represented graphically using bar plots, but the bars have to be plotted for each of the categories of the independent variable separately. This means we need to think carefully about what is the substantive nature of the relationship between both variables. Thus we may want to know:\n\n1.  How the distribution of perception of necessities varies between different economic positions.\n2.  The socioeconomic composition of those who think TVs are necessary compared to those that think TVs are only desirable goods.\n\nThe first seems to be a more plausible relation. It makes sense that we should care whether people with greater attachment to the labour market are more or less likely to consider TVs a necessity compared to those without.\n\nThe first bar plot we will create is a stacked bar chart.\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#stacked bar chart\nggplot(data = omni[complete.cases(omni$tv) & !is.na(omni$paidwork) ,] , \n       aes(x=paidwork)) +\n  geom_bar(stat=\"count\", aes(fill=tv)) \n```\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-29-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\nIf we are interested in comparing the proportions within each group, particularly if there are large differences in raw counts, we can also stack them to add to 100%:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#stacked bar chart up to 100%\nomni |> \n  drop_na(tv, paidwork) |> \n  ggplot(aes(x=paidwork)) +\n  geom_bar(stat=\"count\", aes(fill=tv), position=\"fill\") +\n  scale_y_continuous(labels = scales::percent)\n```\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\nWe can also build a **clustered bar chart** which we can create in two different ways. The first is the classic clustered bar chart using the option **position=\"dodge\" (position=\"dodge2\" will leave a space between the bars)**\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# clustered bar chart\nomni |> \n  drop_na(tv, paidwork) |> \n  ggplot( aes(x=paidwork)) +\n  geom_bar(stat=\"count\", aes(fill=tv), \n           position=\"dodge\") \n```\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\nTo add percentages to a clustered bar chart is a bit cumbersome but here is a possible solution which basically involves calculating directly the proportions before plotting them. It requires an additional package called **ggstats** for geom_bar() to recognise proportions as the quantity to plot\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nomni |> \n  drop_na(tv, paidwork) |> \n  group_by (paidwork, tv) |>\n  count() |> \n  ggplot(aes(x=paidwork, fill = tv, weight = n, \n              by = tv, y = after_stat(prop))) +\n  geom_bar(stat=\"prop\", \n           position=\"dodge\") +\n  scale_y_continuous(labels = scales::percent)\n```\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\nRather than clustering within the same graph, an alternative is to use faceting:\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# \"faceted\" clustered bar chart\nomni |> \n  drop_na(tv, paidwork) |> \n  ggplot(aes(x=tv)) +\n  geom_bar(stat=\"count\") + \n  facet_wrap(~paidwork)\n```\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-33-1.png){width=672}\n:::\n:::\n\n\n\n\n\n\n\n\nAnd we can obviously add labels and titles using the same functions as before.\n\n## Exercise II\n\nWrite the code to produce the contingency table and clustered and stacked bar charts below. Describe the bivariate distribution of item \"appropriate clothes for a job interview\" (variable *jobfrock*) across the educational categories of variable *graduate*.\n\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n    Graduates Not Graduates \n          347          1582 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nNecessary Desirable \n     1236       643 \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               \n                Necessary Desirable\n  Graduates         71.39     28.61\n  Not Graduates     64.46     35.54\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](03_categorical_files/figure-html/unnamed-chunk-34-2.png){width=672}\n:::\n:::\n",
    "supporting": [
      "03_categorical_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}